clients/urls.py
from django.urls import path

from .views import (
    client_list,
    client_create,
    client_detail,
    client_update,
    client_delete,
    order_create,
    order_list,
    order_update,
    order_detail,
    product_create,
    product_list,
)


app_name = "clients"
urlpatterns = [
    path("listar", client_list, name="client-list"),
    path("cadastrar", client_create, name="client-create"),
    path("<int:pk>/detalhes", client_detail, name="client-detail"),
    path("<int:pk>/editar", client_update, name="client-update"),
    path("<int:pk>/deletar", client_delete, name="client-delete"),
    path("pedido/cadastrar", order_create, name="order-create"),
    path("pedido/listar", order_list, name="order-list"),
    path("pedido/<int:pk>/editar", order_update, name="order-update"),
    path("pedido/<int:pk>/detalhes", order_detail, name="order-detail"),
    path("produto/cadastrar", product_create, name="product-create"),
    path("produto/listar", product_list, name="product-list"),
]

tw_clients/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("clientes/", include("clients.urls", namespace="clients")),
    path("admin/", admin.site.urls),
]

templates/adminlte/lib/_main_sidebar.html
{% extends 'adminlte/lib/_main_sidebar.html' %}

{% block nav_links %}

  <li class="treeview">
    <a href="#"><i class="fa fa-user"></i> <span>Clientes</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>

    <ul class="treeview-menu">
      <li>
        <a href="{% url 'clients:client-list' %}">
          <i class="fa fa-list"></i> <span>Listagem</span>
        </a>
      </li>
      <li>
        <a href="{% url 'clients:client-create' %}">
          <i class="fa fa-plus"></i> <span>Cadastro</span>
        </a>
      </li>
    </ul>
  </li>

  <li class="treeview">
    <a href="#"><i class="fa fa-shopping-cart"></i> <span>Pedidos</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>

    <ul class="treeview-menu">
      <li>
        <a href="{% url 'clients:order-list' %}">
          <i class="fa fa-list"></i> <span>Listagem</span>
        </a>
      </li>
      <li>
        <a href="{% url 'clients:order-create' %}">
          <i class="fa fa-plus"></i> <span>Cadastro</span>
        </a>
      </li>
    </ul>
  </li>

  <li class="treeview">
    <a href="#"><i class="fa fa-coffee"></i> <span>Produtos</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>

    <ul class="treeview-menu">
      <li>
        <a href="{% url 'clients:product-list' %}">
          <i class="fa fa-list"></i> <span>Listagem</span>
        </a>
      </li>
      <li>
        <a href="{% url 'clients:product-create' %}">
          <i class="fa fa-plus"></i> <span>Cadastro</span>
        </a>
      </li>
    </ul>
  </li>


{% endblock nav_links %}