clients/urls.py
from django.urls import path

from .views import (
    client_list,
    client_create,
    client_detail,
    client_update,
    client_delete,
    order_create,
    order_list,
    order_update,
    order_detail,
    product_create,
    product_list,
)


app_name = "clients"
urlpatterns = [
    path("listar", client_list, name="client-list"),
    path("cadastrar", client_create, name="client-create"),
    path("<int:pk>/detalhes", client_detail, name="client-detail"),
    path("<int:pk>/editar", client_update, name="client-update"),
    path("<int:pk>/deletar", client_delete, name="client-delete"),
    path("pedido/cadastrar", order_create, name="order-create"),
    path("pedido/listar", order_list, name="order-list"),
    path("pedido/<int:pk>/editar", order_update, name="order-update"),
    path("pedido/<int:pk>/detalhes", order_detail, name="order-detail"),
    path("produto/cadastrar", product_create, name="product-create"),
    path("produto/listar", product_list, name="product-list"),
]

tw_clients/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("clientes/", include("clients.urls", namespace="clients")),
    path("admin/", admin.site.urls),
]

clients/models.py
from django.db import models
from django.db.models.signals import m2m_changed


class Client(models.Model):
    GENDER_CHOICES = (
        ("F", "Feminino"),
        ("M", "Masculino"),
        ("N", "Nenhuma das opções"),
    )

    name = models.CharField("Nome", max_length=100, null=False, blank=False)
    birth_date = models.DateField("Data de Nascimento", null=False, blank=False)
    email = models.EmailField("Email", null=False, blank=False)
    occupation = models.CharField("Profissão", max_length=50, null=False, blank=False)
    gender = models.CharField(
        "Sexo", max_length=1, choices=GENDER_CHOICES, blank=False, null=False
    )
    address = models.OneToOneField(
        "clients.Address",
        verbose_name="Endereço",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    def __str__(self):
        return self.name


class Address(models.Model):
    street = models.CharField("Rua", max_length=200, null=False, blank=False)
    number = models.IntegerField("Número", null=False, blank=False)
    complement = models.CharField(
        "Complemento", max_length=200, null=False, blank=False
    )
    neighborhood = models.CharField("Bairro", max_length=50, null=False, blank=False)
    city = models.CharField("Cidade", max_length=50, null=False, blank=False)
    country = models.CharField("País", max_length=50, null=False, blank=False)

    class Meta:
        verbose_name = "Endereço"
        verbose_name_plural = "Endereços"

    def __str__(self):
        return self.street


class Order(models.Model):
    STATUS_CHOICE = (
        ("P", "Pedido Realizado"),
        ("F", "Fazendo"),
        ("E", "Saiu para entrega"),
    )

    client = models.ForeignKey(
        "clients.Client",
        verbose_name="Cliente",
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )
    date = models.DateTimeField("Data", auto_now_add=True)
    value = models.FloatField("Valor", null=False, blank=False)
    status = models.CharField(
        "Status", max_length=1, choices=STATUS_CHOICE, null=False, blank=False
    )
    comments = models.TextField("Observações", blank=True, null=True)
    products = models.ManyToManyField("clients.Product", verbose_name="Produtos")

    class Meta:
        verbose_name = "Pedido"
        verbose_name_plural = "Pedidos"

    def __str__(self):
        return self.client.name


def pre_save_order_receiver(sender, instance, action, **kwargs):
    if action == "post_add" or action == "post_remove" or action == "post_clear":
        products = instance.products.all()
        order_total_price = 0

        for product in products:
            order_total_price += product.value
        instance.value = order_total_price
        instance.save()


m2m_changed.connect(pre_save_order_receiver, sender=Order.products.through)


class Product(models.Model):
    name = models.CharField("Nome", max_length=50, null=False, blank=False)
    description = models.TextField("Descrição")
    value = models.FloatField("Valor", null=False, blank=False)

    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"

    def __str__(self):
        return self.name

clients/forms/address_forms.py
from django import forms

from clients.models import Address


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = "__all__"

clients/forms/client_forms.py
from django import forms

from clients.models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = "__all__"

clients/forms/order_forms.py
from django import forms

from clients.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ["value"]

clients/forms/product_form.py
from django import forms

from clients.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

clients/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Client
from .forms import ClientForm, AddressForm


def client_list(request):
    clients = Client.objects.all()

    context = {"clients": clients}

    return render(request, "clients/client_list.html", context)


def client_create(request):
    client_form = ClientForm()
    address_form = AddressForm()
    if request.method == "POST":
        client_form = ClientForm(request.POST)
        address_form = AddressForm(request.POST)

        if client_form.is_valid() and address_form.is_valid():
            address = address_form.save()
            client = client_form.save(commit=False)
            client.address = address
            client.save()

            return redirect("clients:client-list")
    context = {"client_form": client_form, "address_form": address_form}
    return render(request, "clients/client_form.html", context)


def client_detail(request, pk):
    client = get_object_or_404(Client, pk=pk)

    context = {"client": client}

    return render(request, "clients/client_detail.html", context)


def client_update(request, pk):
    client = get_object_or_404(Client, pk=pk)

    client_form = ClientForm(instance=client)
    address_form = AddressForm(instance=client.address)

    if request.method == "POST":
        client_form = ClientForm(request.POST, instance=client)
        address_form = AddressForm(request.POST, instance=client.address)

        if client_form.is_valid() and address_form.is_valid():
            address = address_form.save()
            client = client_form.save(commit=False)
            client.address = address
            client.save()

            return redirect("clients:client-detail", pk=client.pk)
    context = {"client_form": client_form, "address_form": address_form}
    return render(request, "clients/client_form.html", context)


def client_delete(request, pk):
    client = get_object_or_404(Client, pk=pk)

    if request.method == "POST":
        client.address.delete()
        client.delete()

        return redirect("clients:client-list")
    context = {"client": client}
    return render(request, "clients/client_confirm_delete.html", context)

clients/views/client_views.py
from django.shortcuts import render, redirect, get_object_or_404

from clients.models import Client
from clients.forms import ClientForm, AddressForm


def client_list(request):
    clients = Client.objects.all()

    context = {"clients": clients}

    return render(request, "clients/client_list.html", context)


def client_create(request):
    client_form = ClientForm()
    address_form = AddressForm()
    if request.method == "POST":
        client_form = ClientForm(request.POST)
        address_form = AddressForm(request.POST)

        if client_form.is_valid() and address_form.is_valid():
            address = address_form.save()
            client = client_form.save(commit=False)
            client.address = address
            client.save()

            return redirect("clients:client-list")
    context = {"client_form": client_form, "address_form": address_form}
    return render(request, "clients/client_form.html", context)


def client_detail(request, pk):
    client = get_object_or_404(Client, pk=pk)

    context = {"client": client}

    return render(request, "clients/client_detail.html", context)


def client_update(request, pk):
    client = get_object_or_404(Client, pk=pk)

    client_form = ClientForm(instance=client)
    address_form = AddressForm(instance=client.address)

    if request.method == "POST":
        client_form = ClientForm(request.POST, instance=client)
        address_form = AddressForm(request.POST, instance=client.address)

        if client_form.is_valid() and address_form.is_valid():
            address = address_form.save()
            client = client_form.save(commit=False)
            client.address = address
            client.save()

            return redirect("clients:client-detail", pk=client.pk)
    context = {"client_form": client_form, "address_form": address_form}
    return render(request, "clients/client_form.html", context)


def client_delete(request, pk):
    client = get_object_or_404(Client, pk=pk)

    if request.method == "POST":
        client.address.delete()
        client.delete()

        return redirect("clients:client-list")
    context = {"client": client}
    return render(request, "clients/client_confirm_delete.html", context)

clients/views/order_views.py
from django.shortcuts import render, redirect, get_object_or_404

from clients.forms import OrderForm
from clients.models import Order


def order_create(request):
    order_form = OrderForm()

    if request.method == "POST":
        order_form = OrderForm(request.POST)

        if order_form.is_valid():
            order_form.save()

            return redirect("clients:order-list")

    context = {"title": "Cadastrar Pedido", "order_form": order_form}

    return render(request, "clients/order_form.html", context)


def order_list(request):
    orders = Order.objects.select_related("client").all()

    context = {"orders": orders}

    return render(request, "clients/order_list.html", context)


def order_update(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order_form = OrderForm(instance=order)

    if request.method == "POST":
        order_form = OrderForm(request.POST, instance=order)

        if order_form.is_valid():
            order_form.save()

            return redirect("clients:order-list")

    context = {"order_form": order_form}

    return render(request, "clients/order_form.html", context)


def order_detail(request, pk):
    order = get_object_or_404(Order, pk=pk)

    context = {"order": order}

    return render(request, "clients/order_detail.html", context)

clients/views/product_views.py
from django.shortcuts import render, redirect

from clients.forms import ProductForm
from clients.models import Product


def product_create(request):
    product_form = ProductForm()

    if request.method == "POST":
        product_form = ProductForm(request.POST)

        if product_form.is_valid():
            product_form.save()

            return redirect("clients:product-list")

    context = {"title": "Cadastrar Produto", "product_form": product_form}

    return render(request, "clients/product_form.html", context)


def product_list(request):
    products = Product.objects.all()

    context = {"products": products}

    return render(request, "clients/product_list.html", context)

clients/templates/clients/client_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <section class="box box-default">
    <div class="box-header with-border">
      <h1 class="box-title">Tem certeza que deseja remover esse cliente?</h1>
    </div>

    <div class="box-body">
      <p><strong>Nome:</strong> {{ client.name }}</p>
      <p><strong>Profissão</strong> {{ client.occupation }}</p>
      <p><strong>Data de Nascimento:</strong> {{ client.birth_date }}</p>
      <p><strong>Email:</strong> {{ client.email }}</p>
      <p><strong>Sexo:</strong> {{ client.gender }}</p>
      <hr>
      <h2>Endereço</h2>
      <p><strong>Rua:</strong> {{ client.address.street }}</p>
      <p><strong>Bairro:</strong> {{ client.address.neighborhood }}</p>
      <p><strong>Cidade:</strong> {{ client.address.city }}</p>

      <form method="POST" class="mt-2">
        {% csrf_token %}

        <button type="submit" class="btn btn-danger">Sim, tenho certeza</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">Não, me leve de volta</a>
      </form>
    </div>

  </section>
{% endblock content %}

clients/templates/clients/client_detail.html
{% extends 'base.html' %}

{% block content %}
  <section class="box box-default">
    <div class="box-header with-border">
      <h1 class="box-title">Detalhes do Cliente</h1>
    </div>

    <div class="box-body">
      <p><strong>Nome:</strong> {{ client.name }}</p>
      <p><strong>Profissão</strong> {{ client.occupation }}</p>
      <p><strong>Data de Nascimento:</strong> {{ client.birth_date }}</p>
      <p><strong>Email:</strong> {{ client.email }}</p>
      <p><strong>Sexo:</strong> {{ client.gender }}</p>
      <hr>
      <h2>Endereço</h2>
      <p><strong>Rua:</strong> {{ client.address.street }}</p>
      <p><strong>Bairro:</strong> {{ client.address.neighborhood }}</p>
      <p><strong>Cidade:</strong> {{ client.address.city }}</p>
    </div>

  </section>
{% endblock content %}

clients/templates/clients/client_form.html
{% extends 'base.html' %}

{% load filters %}

{% block content %}
  <form method="POST">
    {% csrf_token %}

    <h4>Dados do cliente</h4>
    {% for field in client_form %}
      {% ifnotequal field.label "Endereço" %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field|addclass:"form-control" }}
          {{ field.errors }}
        </div>
      {% endifnotequal %}
    {% endfor %}

    <hr>
    <h4>Endereço</h4>
    {% for field in address_form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|addclass:"form-control" }}
        {{ field.errors }}
      </div>
    {% endfor %}

    <div><input type="submit" value="Salvar" class="btn btn-primary"></div>
  </form>
{% endblock content %}

clients/templates/clients/client_list.html
{% extends 'base.html' %}

{% block content %}
  <table class="table">
    <thead>
      <tr>
        <th>Nome</td>
        <th>Data de Nascimento</td>
        <th>Sexo</td>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for client in clients %}
        <tr>
          <td><a href="{% url 'clients:client-detail' pk=client.pk %}">{{ client.name }}</a></td>
          <td>{{ client.birth_date }}</td>
          <td>{{ client.gender }}</td>
          <td>
            <a href="{% url 'clients:client-update' pk=client.pk %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'clients:client-delete' pk=client.pk %}" class="btn btn-danger">Deletar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <a href="{% url 'clients:client-create' %}" class="btn btn-primary">Cadastrar</a>
{% endblock content %}

clients/templates/clients/order_detail.html
{% extends 'base.html' %}

{% block content %}
  <section class="box box-default">
    <div class="box-header with-border">
      <h1 class="box-title">Detalhes do Pedido</h1>
    </div>

    <div class="box-body">
      <p><strong>Cliente:</strong> {{ order.client }}</p>
      <p><strong>Data:</strong> {{ order.date }}</p>
      <p><strong>Valor:</strong> R${{ order.value }}</p>
      <p><strong>Status:</strong> {{ order.status }}</p>
      <p><strong>Descrição:</strong> {{ order.comments }}</p>

      <hr>
      <h4>Lista de Produtos</h4>
      <ul>
        {% for product in order.products.all %}
          <li>{{ product }}</li>
        {% endfor %}
      </ul>
    </div>

  </section>
{% endblock content %}

clients/templates/clients/order_form.html
{% extends 'base.html' %}

{% load filters %}

{% block content %}
  <section class="box box-default">
    <div class="box-header with-border">
      <h1 class="box-title">{{ title }}</h1>
    </div>

    <div class="box-body">
      <form method="POST">
        {% csrf_token %}
        {% for field in order_form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|addclass:"form-control" }}
            {{ field.errors }}
          </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Salvar</button>
      </form>
    </div>
  </section>
{% endblock content %}

clients/templates/clients/order_list.html
{% extends 'base.html' %}

{% block content %}
  <table class="table">
    <thead>
      <tr>
        <th>Cliente</td>
        <th>Data</td>
        <th>Valor</th>
        <th>Status</td>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
        <tr>
          <td><a href="{% url 'clients:order-detail' pk=order.pk %}">{{ order.client }}</a></td>
          <td>{{ order.date }}</td>
          <td>{{ order.value }}</td>
          <td>{{ order.status }}</td>
          <td>
            <a href="{% url 'clients:order-update' pk=order.pk %}" class="btn btn-warning">Editar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <a href="{% url 'clients:order-create' %}" class="btn btn-primary">Cadastrar</a>
{% endblock content %}

clients/templates/clients/product_form.html
{% extends 'base.html' %}

{% load filters %}

{% block content %}
  <section class="box box-default">
    <div class="box-header with-border">
      <h1 class="box-title">{{ title }}</h1>
    </div>

    <div class="box-body">
      <form method="POST">
        {% csrf_token %}
        {% for field in product_form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|addclass:"form-control" }}
            {{ field.errors }}
          </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Salvar</button>
      </form>
    </div>
  </section>
{% endblock content %}

clients/templates/clients/product_list.html
{% extends 'base.html' %}

{% block content %}
  <table class="table">
    <thead>
      <tr>
        <th>Nome</td>
        <th>Valor</td>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
        <tr>
          <td><a href="#">{{ product.name }}</a></td>
          <td>{{ product.value }}</td>
          <td>
            <a href="#" class="btn btn-warning">Editar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <a href="{% url 'clients:product-create' %}" class="btn btn-primary">Cadastrar</a>
{% endblock content %}